### ISSUE TITLE
關於英文轉中文的bug

### ISSUE THREAD

**Issue by hugobug** [danleetw/ebook#3]
首先，軟體原先設定上是先直排，再去做文字的轉換。這在原本的中文之間的轉換並沒有問題，然而，英文書籍本身是橫排格式，當轉檔程序先行直排，再轉換文字的過程中，產生的輸出檔，會存在無效翻譯，亦或者字母直排。我並不知道，是否存在單一個案的可能，目前的實測手上的英文書籍轉換都有這樣的困擾。

**Comment by danleetw** [comment]
是否試試把直排功能關閉,直排功能只是多個直排參數而已,應該不會影響才對
